
#from ..dfp_app.models import Records
#from django.core.exceptions import ValidationError


def validate_dublicate(bin_hash):
    pass